### ISSUE TITLE
Commit ID for Hugging Face not Available

### ISSUE THREAD

**Issue by dipikakhullar** [JiwanChung/tapm#20]
Hi, this requirement has an issue with installing, the specific commit ID has been merged into master and using the tip of master causes issues in running the code. Please advise. I have pasted the requirement from the requirements.txt below

git+https://github.com/huggingface/transformers@155c782a3ccd103cf63ad48a2becd7c76a7d2115#egg=transformers

**Comment by JiwanChung** [comment]
Please reopen if you have further inquiries.
