### ISSUE TITLE
no_gt_sos

### ISSUE THREAD

**Issue by Dobby114** [JiwanChung/tapm#24]
I print the network structure of no_gt_sos model，which is found to be different from that in your paper. There is no attention module in the encoder, but there is an additional context_ Linear module, what is this?
![1](https://user-images.githubusercontent.com/66785750/162601968-9dd0583a-6923-4128-9773-83a020df1b1f.png)

**Comment by JiwanChung** [comment]
context_linear module embeds temporal neighbour representations using the respective linear layers.
While an attention module combined with a relative temporal position embeddings yields similar results to this, we mainly use this module for faster computation.
